name             'workstation'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'All Rights Reserved'
description      'Installs/Configures workstation'
version          '0.2.1'
